# -*- coding: utf-8 -*-
"""pandas_profiling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DtRXkGCJYAMb-Hdw6uFbnmBtJIbDf2Ul
"""

import pandas as pd

df = pd.read_csv('titanic.csv')

df.head()

# This installs the ydata_profiling library, which is used for automatic data analysis and
# generating detailed reports & !is used to run this command in a Jupyter Notebook or similar environments
!pip install ydata_profiling

# #ydata_profiling is a Python library used for generating automated reports for Exploratory Data Analysis (EDA).
from ydata_profiling import ProfileReport
prof = ProfileReport(df)

# # exports the generated report into an HTML file named 'output.html opened into any web browser
prof.to_file(output_file='output.html')